### ISSUE TITLE
Testing need for GPT: Launch an Ansible Playbook thru AAP

### ISSUE THREAD

**Issue by jasperchui** [janus-idp/software-templates#156]

**Comment by josephca** [comment]
Hi, @kadel, can you close it if the test is done?

**Comment by kadel** [comment]
If this is about this template https://github.com/janus-idp/software-templates/tree/e4e63022bbcda740aa2be77ead04a27cd9436d90/templates/github/launch-ansible-job 
than I've tested it and it is broken, bug filed here https://github.com/janus-idp/software-templates/issues/161

**Comment by josephca** [comment]
> ~If this is about this template https://github.com/janus-idp/software-templates/tree/e4e63022bbcda740aa2be77ead04a27cd9436d90/templates/github/launch-ansible-job than I've tested it and it is broken, bug filed here #161~
> 
> Sorry, mistake, got it confused with launch and ansible **job**. There is no template for launching ansible **Playbook**. What is supposed to be tested here? @josephca @jasperchui

@schultzp2020 can you provide the answer? thanks.

**Comment by schultzp2020** [comment]
@josephca we cannot proceed with the QE issue until the associated ENG issue is complete. To my knowledge @kadel has taken over the ENG issue.

**Comment by kadel** [comment]
>To my knowledge @kadel has taken over the ENG issue.

no, he did not. Is there even an ENG issue?

**Comment by schultzp2020** [comment]
@kadel we were talking about this in slack. I guess the ENG issue is the epic, I will fix it. 
PR: https://github.com/janus-idp/software-templates/pull/133
Issue: https://github.com/janus-idp/software-templates/issues/128

**Comment by kadel** [comment]
> @kadel we were talking about this in slack
I thought that was just about reviewing #133

https://github.com/janus-idp/software-templates/pull/133 and  https://github.com/janus-idp/software-templates/issues/128 is about creating an ansible template. Doe creating=launching?

**Comment by schultzp2020** [comment]
> > @kadel we were talking about this in slack
> > I thought that was just about reviewing #133
> 
> #133 and #128 is about creating an ansible template. Does creating=launching?

@jasperchui do you know?
