### ISSUE TITLE
GPT: Create an Ansible Playbook and push to repo

### ISSUE THREAD

**Issue by schultzp2020** [janus-idp/software-templates#173]
### Template Description

_Details to follow_

### 👀 Have you spent some time to check if this template request has been raised before?

- [X] I checked and didn't find any similar issues

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/janus-idp/.github/blob/main/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by jasperchui** [comment]
No longer needed https://github.com/janus-idp/software-templates/issues/193
