### ISSUE TITLE
Doc: improve the root README

### ISSUE THREAD

**Issue by schultzp2020** [janus-idp/software-templates#189]
### What do you want to improve?

[root README](https://github.com/janus-idp/software-templates/blob/main/README.md).

### What is the current documentation?

N/A

### What is the new documentation?

Add a basic README that includes the following information:

- Description of the repository
- How to install the templates
- Best practices on configuring templates

**Comment by kadel** [comment]
replaced by https://github.com/janus-idp/software-templates/issues/193
