### ISSUE TITLE
Add Maven build step to Quarkus Tekton pipeline

### ISSUE THREAD

**Issue by davgordo** [janus-idp/software-templates#21]
Existing pipeline runs a Git clone and then a Buidah build, but no Java artifact is built to include in the image. Include a maven build step.

**Comment by davgordo** [comment]
I think something like this will work: https://github.com/acme-idp-001/software-templates/blob/1372c5c678da0b5dd34cba2cd4e1457b60c2ce9a/scaffolder-templates/quarkus-web-template/skeleton/.helm/build/templates/pipeline.yaml#L32-L47
(PR pending)

**Comment by marshallpowell** [comment]
May be able to leverage this software template from Raff's demo.
