### ISSUE TITLE
Publish component images to the internal OpenShift container image registry by default

### ISSUE THREAD

**Issue by davgordo** [janus-idp/software-templates#22]
Adjust Quarkus build Helm chart so that the resulting Tekton pipeline is configured to publish to the internal OpenShift container image registry by default

**Comment by davgordo** [comment]
May need a RoleBinding

**Comment by davgordo** [comment]
In order to pull the image from dev/test/prod, we will need some rbac to enable access to the image published in the build namespace.

**Comment by marshallpowell** [comment]
This story appears to be dependent on Task 1.

We also need to consider adding in an external registry like Quay.
