### ISSUE TITLE
GPT: Add Tech Docs (a documentation template)

### ISSUE THREAD

**Issue by christophe-f** [janus-idp/software-templates#92]
The template will ask which component to link with and create a new repo.

```
EntityPicker:
        type: string
        ui:field: EntityPicker
        ui:options:
          catalogFilter:
            - kind: component
```

For example a component with the name `node-website` will have a new repo `node-website-techdocs`

The template skeleton will contain the `mkdocs.yaml` with the `/docs` folder contains a sample index.md
It will also create the GitHub Action pipeline. For example the one from Showcase: https://github.com/janus-idp/backstage-showcase/blob/main/.github/workflows/techdocs.yaml

No need to do Tekton pipeline yet.

Issues in Epic
- https://github.com/janus-idp/software-templates/issues/154 [Doc]
- https://github.com/janus-idp/software-templates/issues/155 [QE]

**Comment by jasperchui** [comment]
Reopen and convert to EPIC and capture doc and testing requirements.
